### ISSUE TITLE
Returning Task.FromResult(false) throws NullReferenceException

### ISSUE THREAD

**Issue by andriivitiv** [Singulink/RuntimeNullables#3] opened 2021-01-29 23:11 UTC
```
Unhandled exception. System.NullReferenceException: Task result nullability contract was broken.
   at RuntimeNullables.ThrowHelpers.ThrowOutputNull(String message)
   at FodyTest.Program.DoSomethingAsync() in /home/andrii/development/FodyTest/FodyTest/Program.cs:line 17
   at FodyTest.Program.Main(String[] args) in /home/andrii/development/FodyTest/FodyTest/Program.cs:line 9
   at FodyTest.Program.<Main>(String[] args)
```

Minimal reproducible example:

```cs
using System.Threading.Tasks;

namespace FodyTest
{
    class Program
    {
        static Task Main(string[] args)
        {
            return DoSomethingAsync();
        }

        static Task<bool> DoSomethingAsync()
        {
            // Returning False throws the exception
            // Returning True works fine
            return Task.FromResult(false);
        }
    }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup>
        <WeaverConfiguration>
            <Weavers>
                <RuntimeNullables CheckOutputs="true" CheckNonPublic="true" />
            </Weavers>
        </WeaverConfiguration>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="RuntimeNullables.Fody" Version="0.9.3" />
    </ItemGroup>

</Project>
```

**Comment by mikernet** [comment] 2021-01-29 23:22
Thank you for the report, I have reproduced and traced the problem. Please give me a few minutes here, I will let you know when a fix is posted.

**Comment by mikernet** [comment] 2021-01-30 01:11
Fixed via https://github.com/Singulink/RuntimeNullables/commit/4bd7513b5b111033278c94b3f2a01026ddd683db

**Comment by mikernet** [comment] 2021-01-30 01:13
Version 0.9.4 is publishing to nuget right now, should be available in a few minutes - please give it a try and let me know if you have any other problems.

**Comment by andriivitiv** [comment] 2021-01-30 02:28
Thanks for quick fix. These problems are fixed but I still have another. I think it's something related to using `ref` and `foreach` in the same method.
```
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at FodyTest.Program.PreProcessYaml(String& yaml)
   at FodyTest.Program.Main(String[] args) in /home/andrii/development/FodyTest/FodyTest/Program.cs:line 16
```

```cs
    class Program
    {
        static readonly Dictionary<string, string> vars = new()
        {
            {"foo", "bar"},
        };

        static void Main(string[] args)
        {
            string str = "foo";
            PreProcessYaml(ref str);
        }

        static void PreProcessYaml(ref string yaml)
        {
            foreach (var variable in vars)
            {
            }
        }
    }
```

**Comment by mikernet** [comment] 2021-01-30 03:13
Interesting, traced the issue - has to do with the `finally` block added by the foreach right before the return. Let me see what I can do here.

**Comment by mikernet** [comment] 2021-01-30 03:23
Can you try something for me real quick - if you add any dummy code like `Console.Write("");` after the `foreach` block, does it work?

**Comment by andriivitiv** [comment] 2021-01-30 03:36
Yes - adding `Console.Write("");` or even `return;` fixes the issue

**Comment by mikernet** [comment] 2021-01-30 03:50
Thank you for your concise minimal repros that made tracing this issue a piece of cake :)

The `return;` trick only works in debug builds - release builds will optimize out the redundant return and fail. Fix for this issue incoming shortly!

**Comment by mikernet** [comment] 2021-01-30 05:05
I may have come across a Mono Cecil bug - tracking the issue here https://github.com/jbevain/cecil/issues/714.

Investigating workarounds in the meantime.

**Comment by mikernet** [comment] 2021-01-30 07:36
Fixed via https://github.com/Singulink/RuntimeNullables/commit/0654c80edd1fd1eb805691ef223eddaec0d06325.

New nuget package going up right now, should be available to update in a few minutes.

**Closed as completed by mikernet** 2021-01-30 07:36 UTC
Labels: bug

**Comment by Trojaner** [comment] 2021-01-31 15:57
Seems like the same issue happens when using Enums, is that fixed too?

**Comment by mikernet** [comment] 2021-01-31 15:57
@Trojaner Give the updated package a try, it should be fixed.

**Comment by Trojaner** [comment] 2021-01-31 16:01
This issue happens with 0.9.5, which appears to be the latest version.

I think it happens when enums return 0.

![image](https://user-images.githubusercontent.com/1809172/106389843-a1a54680-63f6-11eb-8b75-54149df29b31.png)

![image](https://user-images.githubusercontent.com/1809172/106389848-aec23580-63f6-11eb-9946-667db285cf77.png)

![image](https://user-images.githubusercontent.com/1809172/106389855-b550ad00-63f6-11eb-801c-2c8400ceabe3.png)

The return value can not be null here

**Comment by mikernet** [comment] 2021-01-31 16:06
Ah, I see the issue, I fixed it for sync task results but not async. Update coming shortly, give me a bit.

**Comment by mikernet** [comment] 2021-01-31 16:27
Package is published, give er a go :)

**Comment by Trojaner** [comment] 2021-01-31 22:54
Thank you, I can confirm that the issue is resolved now.
